 server:
  port: 8081
  address: 10.51.62.230

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campushub?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.campushub: DEBUG

jwt:
  secret: your-secret-key
  expiration: 86400000 # 24 hours